name: JMeter Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz -o jmeter.tgz
          tar -xvzf jmeter.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Tests
        run: |
          mkdir -p result/report
          ./jmeter/bin/jmeter -n -t tests/your-test-plan.jmx -l result/result.jtl -e -o result/report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result/
