name: JMeter Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          mv apache-jmeter-5.5 jmeter

      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter -n -t soho.jmx -l result.jtl -e -o results-html

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-report
          path: results-html
